apiVersion: v1
kind: ConfigMap
metadata:
  name: adodash-config
data:
  corsOrigin: "https://your-web-domain"
  azureAdTenantId: ""
  azureAdClientId: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: adodash-secrets
type: Opaque
stringData:
  databaseUrl: ""
  encryptionKeyBase64: ""

